package org.example.Dao;

import org.example.DataObject.AllUserDO;

public interface AllUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alluser
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alluser
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int insert(AllUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alluser
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int insertSelective(AllUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alluser
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    AllUserDO selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alluser
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int updateByPrimaryKeySelective(AllUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alluser
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int updateByPrimaryKey(AllUserDO record);

    AllUserDO selectByUserName(String username,String password);
}