package org.example.Dao;

import org.example.DataObject.PermissionDO;

public interface PermissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int insert(PermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int insertSelective(PermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    PermissionDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int updateByPrimaryKeySelective(PermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int updateByPrimaryKey(PermissionDO record);
}