package org.example.Dao;

import org.example.DataObject.UserRoleDO;

public interface UserRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int insert(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int insertSelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    UserRoleDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int updateByPrimaryKeySelective(UserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Wed Dec 23 13:17:26 CST 2020
     */
    int updateByPrimaryKey(UserRoleDO record);
}