package org.example.DataObject;

public class AllUserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alluser.id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alluser.name
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alluser.password
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alluser.role_id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alluser.id
     *
     * @return the value of alluser.id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alluser.id
     *
     * @param id the value for alluser.id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alluser.name
     *
     * @return the value of alluser.name
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alluser.name
     *
     * @param name the value for alluser.name
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alluser.password
     *
     * @return the value of alluser.password
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alluser.password
     *
     * @param password the value for alluser.password
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alluser.role_id
     *
     * @return the value of alluser.role_id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alluser.role_id
     *
     * @param roleId the value for alluser.role_id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}