package org.example.DataObject;

public class PermissionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permissionname
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    private String permissionname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permissionname
     *
     * @return the value of permission.permissionname
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public String getPermissionname() {
        return permissionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permissionname
     *
     * @param permissionname the value for permission.permissionname
     *
     * @mbg.generated Wed Dec 23 13:07:41 CST 2020
     */
    public void setPermissionname(String permissionname) {
        this.permissionname = permissionname == null ? null : permissionname.trim();
    }
}